credentials:
  usernames:
    user1:
      name: "User 1"
      password: "$2b$12$sDPMkx3JgLy7aacKEpy1zulhSF6JZKLi7a4Qy5Lp2CCNneWtkacv2"
    user2:
      name: "User 2"
      password: "$2b$12$UTtuS3q1YFR3cZZHskplLe6r.rsPaGcqstWS.h6c5yxjW.6FoKsGW"
cookie:
  expiry_days: 30
  key: "secret"
  name: "streamlit-cookie"