[connections.snowflake]
account = "hburatq-cq35729"
user = "SHIV0ABC"
password = "Kishore@12345"
role = "ACCOUNTADMIN"
warehouse = "TEST1WH"
database = "TEST1DB"
schema = "PUBLIC"
client_session_keep_alive = true